{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "source-repo.serviceAccountName" . }}
  labels:
{{ include "source-repo.labels" . | indent 4 }}
{{- end -}}
